services:
  db:
    image: postgres
    restart: always
    volumes:
      - ${DATA_MOUNT}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
  web:
    image: $BOT_IMAGE:$BOT_TAG
    ports:
      - "$HTTP_PORT:8000"
    entrypoint: "/bin/bash -c 'manage collectstatic --noinput && manage runserver 0.0.0.0:8000'"
    environment:
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_USER=$POSTGRES_USER
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=5432
      - DB_HOST=db
      - SECRET_KEY
      - DEBUG
    depends_on:
      - migrate
  bot:
    image: $BOT_IMAGE:$BOT_TAG
    entrypoint: "manage run_discord_bot"
    environment:
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_USER=$POSTGRES_USER
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=5432
      - DB_HOST=db
      - DISCORD_KEY
      - DISCORD_COMMAND_PREFIX
      - SECRET_KEY
      - DEBUG
    depends_on:
      - migrate
  migrate:
    image: $BOT_IMAGE:$BOT_TAG
    entrypoint: "manage migrate --no-input"
    environment:
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_USER=$POSTGRES_USER
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=5432
      - DB_HOST=db
      - SECRET_KEY
      - DEBUG
    depends_on:
      - db
    restart: on-failure