[tool.poetry]
name = "gam_bot"
version = "0.0.0"
description = "A fun discord bot for my discord server"
authors = ["Cameron Graybill <camerongraybill@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
run_bot = "gam_bot.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^1.7.3"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pylint = "^2.11.1"
bandit = "^1.7.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.mypy]
files = "gam_bot"

[tool.pylint.MASTER]
disable="C"