# Generated by Django 3.2.22 on 2024-09-14 20:48

import async_helpers.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discord_bot", "0004_discorduser_notify_on_startup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="discord_bot.discorduser",
                    ),
                ),
                ("reminder_text", models.TextField()),
                ("reminder_time", models.DateTimeField()),
                ("initial_channel_id", models.PositiveBigIntegerField()),
            ],
            bases=(models.Model, async_helpers.mixins.AsyncModelMixin),
        ),
    ]
