# Generated by Django 5.1.1 on 2024-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creator_id", models.PositiveBigIntegerField()),
                ("reminder_text", models.TextField()),
                ("reminder_time", models.DateTimeField()),
                ("initial_channel_id", models.PositiveBigIntegerField()),
            ],
        ),
    ]
