# Generated by Django 3.2.8 on 2021-11-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discord_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="discord_bot.discorduser",
                    ),
                ),
                ("coins", models.PositiveIntegerField(default=0)),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                ("prediction_text", models.TextField()),
                (
                    "thread_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("open", models.BooleanField(default=True)),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="PredictionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.TextField()),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gam_coins.prediction",
                    ),
                ),
            ],
            options={
                "unique_together": {("prediction", "choice")},
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="Wager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gam_coins.account",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gam_coins.predictionchoice",
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
    ]
