# Generated by Django 3.2.8 on 2021-10-24 20:58
from typing import Sequence

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="GamUser",
            fields=[
                ("discord_id", models.IntegerField(primary_key=True, serialize=False)),
                ("gam_coins", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
