# Generated by Django 3.2.8 on 2021-10-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamuser',
            name='social_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
