# Generated by Django 3.2.8 on 2021-11-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "fill_gam_coins"),
        ("chatbot", "fill_social_score"),
    ]

    operations = []
