# Generated by Django 3.2.8 on 2021-10-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_gamuser_social_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamuser",
            name="social_score",
            field=models.IntegerField(default=0),
        ),
    ]
