# Generated by Django 3.2.8 on 2021-10-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_alter_gamuser_social_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamuser",
            name="discord_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
