# Generated by Django 3.2.8 on 2021-10-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_gamuser_discord_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmojiScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji_id", models.TextField()),
                ("score", models.IntegerField(default=0)),
            ],
        ),
    ]
