# Generated by Django 3.2.8 on 2021-11-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_emojiscore'),
        ('chatbot', '0006_rename_bettor_wager_user'),
    ]

    operations = [
    ]
