# Generated by Django 3.2.8 on 2021-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_merge_0005_emojiscore_0006_rename_bettor_wager_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prediction",
            name="open",
        ),
        migrations.AddField(
            model_name="prediction",
            name="state",
            field=models.CharField(
                choices=[
                    ("AW", "ACCEPTING_WAGERS"),
                    ("WR", "WAITING_FOR_RESOLUTION"),
                    ("RE", "RESOLVED"),
                ],
                default="AW",
                max_length=2,
            ),
        ),
    ]
