# Generated by Django 3.2.8 on 2021-11-05 02:32

import async_helpers.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('discord_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
            bases=(models.Model, async_helpers.mixins.AsyncModelMixin),
        ),
    ]
