# Generated by Django 3.2.8 on 2021-11-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="last_known_nickname",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
