# Generated by Django 3.2.8 on 2021-11-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0002_discorduser_last_known_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="last_known_account_name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
