# Generated by Django 3.2.8 on 2021-11-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0003_discorduser_last_known_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="notify_on_startup",
            field=models.BooleanField(default=False),
        ),
    ]
