name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        python3 -m venv ./venv
        ./venv/bin/pip install poetry==1.1.11 poetry-dynamic-versioning==0.13.1
        APP_VERSION=$(./venv/bin/poetry version -s)
        docker build . --file Dockerfile --tag gam-bot:$APP_VERSION
