name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.0"
    - name: Set up environment
      run: |
        pip install poetry
        poetry install
    - name: Running Bandit
      run: poetry run bandit -r ./src
    - name: Running Black
      run: poetry run black ./src --check
    - name: Running Mypy
      run: poetry run mypy
    - name: Running Pylint
      run: cd src && poetry run pylint --rcfile ../pyproject.toml ./chatbot/ ./gam/ ./manage.py  ./async_helpers/ ./easy_messages/ ./gam_coins/ ./lmgtfy/ ./social_score/ && cd ..
    - name: Running Pytest
      run: poetry run pytest
