name: Linting

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Set up environment
        run: poetry install

      - name: Running Ruff Format
        run: poetry run ruff format --check

      - name: Running Mypy
        working-directory: src
        run: poetry run mypy --config-file ../pyproject.toml .

      - name: Ruff Lint
        working-directory: src
        run: poetry run ruff check

      - name: Running Tests
        working-directory: src
        run: poetry run manage test
